name: Deploy to GitHub Pages

on:
  # Déclenche le workflow chaque fois qu'un push est effectué sur la branche `main`
  # Si vous utilisez une autre branche, remplacez `main` par son nom
  push:
    branches: [main]
  # Permet d'exécuter ce workflow manuellement depuis l'onglet Actions sur GitHub
  workflow_dispatch:

# Autorisations nécessaires pour cloner le dépôt et déployer les pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install, build, and upload site
        uses: withastro/action@v3
        with:
          node-version: 20
          package-manager: npm
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
